### ISSUE TITLE
搭配node接口实现日志存储解析

### ISSUE THREAD

**Issue by yonwoo9** [adminV/dataAcquisition#2]
大佬，想问下 node接口实现日志存储解析 的解决思路是什么，不知道怎么操作比较好。另外发现个问题，因为目前数据上传触发只有页面跳转和手动触发。但是如果在当前页面进行操作，如点击事件，然后直接关闭当前页，后台没法获取相应的操作数据，可以在页面关闭的时候，添加触发上传操作，或是检测关闭前是否有进行操作，有则提交，无则免之

**Comment by VienLi** [comment]
在Vue版本中已经将数据上报修改为实时上报，另外Node服务端日志存储的代码分为两种：

1. 本地文件 https://github.com/adminV/dataAcquisition/blob/master/server/app.js
2. MongoDB存储 https://github.com/adminV/Vue-dataAc-server
